
server:
  port: 44440

spring:
  quartz:
    job-store-type: memory
    scheduler-name: p-quartz-scheduler
    properties:
      # http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigMain.html 참고
      org.quartz.threadPool.threadCount: 3
      org.quartz.scheduler.instanceName: p-instance
