
logging:
  level:
    org.quartz: DEBUG

server:
  port: 44440

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dockerhost:13350/testdb
    username: root
    password: rootpass
    # https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
    hikari:
      maximum-pool-size: 5 # hikari 가 커넥션 풀에 최대로 가질 수 있는 사이즈


  quartz:
    # job-store-type: memory
    job-store-type: jdbc
    scheduler-name: p-quartz-scheduler
    properties:
      # http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/#choose-a-topic: 참고
      org.quartz.threadPool.threadCount: 5

      # scheduler
      org.quartz.scheduler.threadName: ppp-thr
      org.quartz.scheduler.instanceName: ppp-ins
      org.quartz.scheduler.instanceId: AUTO

      # jobStore
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartzDataSource

      # dataSource
      org.quartz.dataSource.quartzDataSource.driver: com.mysql.cj.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mysql://dockerhost:13350/testdb
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: rootpass
      org.quartz.dataSource.quartzDataSource.provider: hikaricp # hikaricp 없으면 다른 provider 를 임포트 해주던가 해야함. (아니면 기본으로..)

      # dataSource 를 hikari 로 사용하면 관련 설정도 같이 쓸 수 있다. : https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      # dataSource 가 connection pool 에서 생성할 수 있는 최대 커넥션 개수.
      org.quartz.dataSource.quartzDataSource.maxConnections: 15

    jdbc:
      initialize-schema: never
      platform: mysql



  mail:
    host: smtp.naver.com
    port: 587
    username: pasudo123@naver.com
    # naver password 참고 : https://help.naver.com/support/contents/contents.help?serviceNo=532&categoryNo=11047
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

## job 식별 아이덴티티
custom-worker:
  simple-cron-worker:
    id: simple-cron-worker-01



